### ISSUE TITLE
When deploying codepipeline.yaml: Plugin 'ServerlessAppPlugin' raised an exception: 'Session' object has no attribute 'get_partition_for_region' 

### ISSUE THREAD

**Issue by zgre** [aws/aws-sam-cli#3789]
### Description:

When upgraded to 1.4.3 version of sam cli noticed failure when deploying.

### Steps to reproduce:

Trying to deploy a pipeline just with different FeatureGitBranch

sam deploy -g -t codepipeline.yaml --stack-name dev-pipeline --capabilities=CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND --parameter-overrides="FeatureGitBranch=api-subdomain"

2022-03-31 17:10:28 Plugin 'ServerlessAppPlugin' raised an exception: 'Session' object has no attribute 'get_partition_for_region'
Traceback (most recent call last):
  File "samtranslator/plugins/__init__.py", line 133, in act
  File "samtranslator/metrics/method_decorator.py", line 96, in wrapper_cw_timer
  File "samtranslator/plugins/application/serverless_app_plugin.py", line 114, in on_before_transform_template
  File "samtranslator/region_configuration.py", line 55, in is_service_supported
AttributeError: 'Session' object has no attribute 'get_partition_for_region'
Traceback (most recent call last):
  File "samcli/__main__.py", line 12, in <module>
  File "click/core.py", line 829, in __call__
  File "click/core.py", line 782, in main
  File "click/core.py", line 1259, in invoke
  File "click/core.py", line 1066, in invoke
  File "click/core.py", line 610, in invoke
  File "samcli/lib/cli_validation/image_repository_validation.py", line 92, in wrapped
  File "click/decorators.py", line 73, in new_func
  File "click/core.py", line 610, in invoke
  File "samcli/lib/telemetry/metric.py", line 166, in wrapped
  File "samcli/lib/telemetry/metric.py", line 124, in wrapped
  File "samcli/lib/utils/version_checker.py", line 41, in wrapped
  File "samcli/cli/main.py", line 87, in wrapper
  File "samcli/commands/_utils/cdk_support_decorators.py", line 38, in wrapped
  File "samcli/commands/deploy/command.py", line 193, in cli
  File "samcli/commands/deploy/command.py", line 255, in do_cli
  File "samcli/commands/deploy/guided_context.py", line 559, in run
  File "samcli/commands/deploy/guided_context.py", line 140, in guided_prompts
  File "samcli/lib/providers/sam_stack_provider.py", line 243, in get_stacks
  File "samcli/lib/providers/sam_stack_provider.py", line 53, in __init__
  File "samcli/lib/providers/sam_base_provider.py", line 189, in get_template
  File "samcli/lib/samlib/wrapper.py", line 68, in run_plugins
  File "samcli/lib/samlib/wrapper.py", line 88, in parse
  File "samtranslator/plugins/__init__.py", line 139, in act
  File "samtranslator/plugins/__init__.py", line 133, in act
  File "samtranslator/metrics/method_decorator.py", line 96, in wrapper_cw_timer
  File "samtranslator/plugins/application/serverless_app_plugin.py", line 114, in on_before_transform_template
  File "samtranslator/region_configuration.py", line 55, in is_service_supported
AttributeError: 'Session' object has no attribute 'get_partition_for_region'
[558295] Failed to execute script __main__

### Observed result:
2022-03-31 17:14:07,231 | Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
2022-03-31 17:14:07,231 | Using config file: samconfig.toml, config environment: default
2022-03-31 17:14:07,231 | Expand command line arguments to:
2022-03-31 17:14:07,231 | --template_file=...codepipeline.yaml --stack_name=dev-pipeline --capabilities=('CAPABILITY_NAMED_IAM', 'CAPABILITY_AUTO_EXPAND') --parameter_overrides={'FeatureGitBranch': 'api-subdomain'} --fail_on_empty_changeset 
2022-03-31 17:14:07,417 | Collected default values for parameters: XXXXX
2022-03-31 17:14:07 Plugin 'ServerlessAppPlugin' raised an exception: 'Session' object has no attribute 'get_partition_for_region'
Traceback (most recent call last):
  File "samtranslator/plugins/__init__.py", line 133, in act
  File "samtranslator/metrics/method_decorator.py", line 96, in wrapper_cw_timer
  File "samtranslator/plugins/application/serverless_app_plugin.py", line 114, in on_before_transform_template
  File "samtranslator/region_configuration.py", line 55, in is_service_supported
AttributeError: 'Session' object has no attribute 'get_partition_for_region'
2022-03-31 17:14:07,434 | Sending Telemetry: {'metrics': [{'commandRun': {'requestId': '181ed136-10f8-4a64-ae6a-824ef5b52283', 'installationId': '8addadde-6eb3-423f-b935-e95ef9e4d900', 'sessionId': '86cc807a-8fc9-4aa4-94e3-c32bbd2ade83', 'executionEnvironment': 'CLI', 'ci': False, 'pyversion': '3.7.10', 'samcliVersion': '1.43.0', 'awsProfileProvided': False, 'debugFlagProvided': True, 'region': 'eu-west-1', 'commandName': 'sam deploy', 'metricSpecificAttributes': {'projectType': 'CFN'}, 'duration': 202, 'exitReason': 'AttributeError', 'exitCode': 255}}]}
2022-03-31 17:14:08,142 | HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443): Read timed out. (read timeout=0.1)
Traceback (most recent call last):
  File "samcli/__main__.py", line 12, in <module>
  File "click/core.py", line 829, in __call__
  File "click/core.py", line 782, in main
  File "click/core.py", line 1259, in invoke
  File "click/core.py", line 1066, in invoke
  File "click/core.py", line 610, in invoke
  File "samcli/lib/cli_validation/image_repository_validation.py", line 92, in wrapped
  File "click/decorators.py", line 73, in new_func
  File "click/core.py", line 610, in invoke
  File "samcli/lib/telemetry/metric.py", line 166, in wrapped
  File "samcli/lib/telemetry/metric.py", line 124, in wrapped
  File "samcli/lib/utils/version_checker.py", line 41, in wrapped
  File "samcli/cli/main.py", line 87, in wrapper
  File "samcli/commands/_utils/cdk_support_decorators.py", line 38, in wrapped
  File "samcli/commands/deploy/command.py", line 193, in cli
  File "samcli/commands/deploy/command.py", line 291, in do_cli
  File "samcli/commands/package/package_context.py", line 104, in run
  File "samcli/lib/providers/sam_stack_provider.py", line 243, in get_stacks
  File "samcli/lib/providers/sam_stack_provider.py", line 53, in __init__
  File "samcli/lib/providers/sam_base_provider.py", line 189, in get_template
  File "samcli/lib/samlib/wrapper.py", line 68, in run_plugins
  File "samcli/lib/samlib/wrapper.py", line 88, in parse
  File "samtranslator/plugins/__init__.py", line 139, in act
  File "samtranslator/plugins/__init__.py", line 133, in act
  File "samtranslator/metrics/method_decorator.py", line 96, in wrapper_cw_timer
  File "samtranslator/plugins/application/serverless_app_plugin.py", line 114, in on_before_transform_template
  File "samtranslator/region_configuration.py", line 55, in is_service_supported
AttributeError: 'Session' object has no attribute 'get_partition_for_region'
[559651] Failed to execute script __main__

### Expected result:

Pipeline should be deployed

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Ubuntu 21.10
2. `sam --version`: 1.43
3. AWS region: eu-west-1

**Comment by hawflau** [comment]
Hey @zgre, it seems your boto3 version is not new enough as `'Session' object has no attribute 'get_partition_for_region'`. If you're using `pip` to install SAM CLI, can you try upgrade `boto3`?

```
pip install boto3 --upgrade
```

**Comment by zgre** [comment]
Hi @hawflau, yes that helped. Tnx

**Comment by chenrui333** [comment]
ran into the similar issue in the github action runs.

```
2022-04-04 18:56:25 Plugin 'ServerlessAppPlugin' raised an exception: 'Session' object has no attribute 'get_partition_for_region'
Traceback (most recent call last):
  File "samtranslator/plugins/__init__.py", line 133, in act
  File "samtranslator/metrics/method_decorator.py", line 96, in wrapper_cw_timer
  File "samtranslator/plugins/application/serverless_app_plugin.py", line 114, in on_before_transform_template
  File "samtranslator/region_configuration.py", line 55, in is_service_supported
AttributeError: 'Session' object has no attribute 'get_partition_for_region'
[1902] Failed to execute script __main__
Traceback (most recent call last):
```

**Comment by hawflau** [comment]
@chenrui333 We have bumped boto3 version in our requirements so it should be fixed in our next release. Meanwhile, you can add `pip install boto3 --upgrade` before `pip install aws-sam-cli`.

**Comment by chenrui333** [comment]
I actually using the default `sam`, which is whatever installed in the virtual-environments 🤦

**Comment by chenrui333** [comment]
yeah, I can try the proposed steps though. Any regression testing improvement per this issue report?

**Comment by qingchm** [comment]
@zgre @chenrui333 our latest release v1.44.0 has addressed this issue! Please update to test if the issue has been resolved! Closing the ticket now, thanks for opening this ticket and let us know if you have any questions!
