### ISSUE TITLE
Bug: v1.78 parses capabilities from samconfig.toml as string instead of list, worked in v1.76

### ISSUE THREAD

**Issue by robwdux** [aws/aws-sam-cli#4934]
### Description:

upgrading from v1.76 to v1.78 causes `sam deploy` to error with a previously working samconfig.toml, expecting a string for capabilities when previously accepted a list which.

`sam deploy --help` does not indicate a change in type.

> --capabilities LIST | List of capabilities that one must specify before AWS Cloudformation can create certain stacks.

### Steps to reproduce:

Attempt to deploy a stack with samconfig.toml providing a list for capabilities.

`capabilities: ["CAPABILITY_IAM"]` or `capabilities: ["CAPABILITY_AUTO_EXPAND", "CAPABILITY_NAMED_IAM", "CAPABILITY_IAM"]`

### Observed result:

```sh
Error: 'str' object has no attribute 'value'
Traceback:
  File "click/core.py", line 1055, in main
  File "click/core.py", line 1657, in invoke
  File "click/core.py", line 1404, in invoke
  File "click/core.py", line 760, in invoke
  File "samcli/lib/cli_validation/image_repository_validation.py", line 92, in wrapped
  File "click/decorators.py", line 84, in new_func
  File "click/core.py", line 760, in invoke
  File "samcli/lib/telemetry/metric.py", line 183, in wrapped
  File "samcli/lib/telemetry/metric.py", line 148, in wrapped
  File "samcli/lib/utils/version_checker.py", line 42, in wrapped
  File "samcli/cli/main.py", line 90, in wrapper
  File "tomlkit/items.py", line 1415, in __str__
  File "tomlkit/items.py", line 1415, in <listcomp>
An unexpected error was encountered while executing "sam deploy".
```
**workaround**

in samconfig.toml, set capabilities to a string.

`capabilitities: "CAPABILITY_AUTO_EXPAND CAPABILITY_NAMED_IAM CAPABILITY_IAM"

### Expected result:

samconfig.toml with as shown in output `capabilities: ["CAPABILITY_AUTO_EXPAND", "CAPABILITY_NAMED_IAM", "CAPABILITY_IAM"]` does not error.

```sh
	Deploying with following values
	===============================
	Stack name                   : <stack-name>
	Region                       : us-east-1
	Confirm changeset            : False
	Disable rollback             : False
	Deployment s3 bucket         : <bucket-name>
	Capabilities                 : ["CAPABILITY_AUTO_EXPAND", "CAPABILITY_NAMED_IAM", "CAPABILITY_IAM"]
	Parameter overrides          : {"<name>": "<value>", "<name>": "<value>"}
	Signing Profiles             : {}
```

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS:
2. `sam --version`:
3. AWS region:

```
# Paste the output of `sam --info` here
```

`Add --debug flag to command you are running`

```
❯ sam --info
{
  "version": "1.78.0",
  "system": {
    "python": "3.11.2",
    "os": "macOS-13.2.1-arm64-arm-64bit"
  },
  "additional_dependencies": {
    "docker_engine": "Not available",
    "aws_cdk": "Not available",
    "terraform": "1.4.2"
  }
}
```

**Comment by mikegrima** [comment]
I wonder if this is the cause of my issue in: https://github.com/aws/aws-sam-cli/issues/4937 🤔

**Comment by moelasmar** [comment]
Thanks @robwdux for raising this issue. I can reproduce this issue. I am working on determining the change that cause this issue.

**Comment by moelasmar** [comment]
this PR https://github.com/aws/aws-sam-cli/pull/4757 that cause this issue.

**Comment by moelasmar** [comment]
I will close this issue as it is duplicate to this issue https://github.com/aws/aws-sam-cli/issues/4937
