### ISSUE TITLE
ImportError: cannot import name 'soft_unicode' from 'markupsafe' in Release 1.38.0

### ISSUE THREAD

**Issue by SamkeetJainMensa** [aws/aws-sam-cli#3661]
I'm building the sam project on github action and since the upgrade of sam-cli to 1.38.0, i'm getting following error when i build project

Python version: `3.10.2` & `3.8.12` (Tried both versions)
Pip version: `pip-22.0.3`
Sam cli version: `1.38.0`

Command: `sam build --template ${SAM_TEMPLATE} --use-container`

Trace:
```
Traceback (most recent call last):
  File "/home/runner/work/_temp/setup-sam-43osIE/bin/sam", line 8, in <module>
    sys.exit(cli())
  File "/home/runner/work/_temp/setup-sam-43osIE/.venv/lib/python3.10/site-packages/click/core.py", line 8[29](https://github.com/mensabrands/dip-app/runs/5243143255?check_suite_focus=true#step:5:29), in __call__
    return self.main(*args, **kwargs)
  File "/home/runner/work/_temp/setup-sam-43osIE/.venv/lib/python3.10/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/runner/work/_temp/setup-sam-43osIE/.venv/lib/python3.10/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/runner/work/_temp/setup-sam-43osIE/.venv/lib/python3.10/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/runner/work/_temp/setup-sam-43osIE/.venv/lib/python3.10/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/runner/work/_temp/setup-sam-43osIE/.venv/lib/python3.10/site-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/runner/work/_temp/setup-sam-43osIE/.venv/lib/python3.10/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/runner/work/_temp/setup-sam-43osIE/.venv/lib/python3.10/site-packages/samcli/lib/telemetry/metric.py", line 166, in wrapped
    raise exception  # pylint: disable=raising-bad-type
  File "/home/runner/work/_temp/setup-sam-43osIE/.venv/lib/python3.10/site-packages/samcli/lib/telemetry/metric.py", line 124, in wrapped
    return_value = func(*args, **kwargs)
  File "/home/runner/work/_temp/setup-sam-43osIE/.venv/lib/python3.10/site-packages/samcli/lib/utils/version_checker.py", line 41, in wrapped
    actual_result = func(*args, **kwargs)
  File "/home/runner/work/_temp/setup-sam-43osIE/.venv/lib/python3.10/site-packages/samcli/cli/main.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/home/runner/work/_temp/setup-sam-43osIE/.venv/lib/python3.10/site-packages/samcli/commands/build/command.py", line 174, in cli
    do_cli(
  File "/home/runner/work/_temp/setup-sam-43osIE/.venv/lib/python3.10/site-packages/samcli/commands/build/command.py", line 220, in do_cli
    from samcli.commands.build.build_context import BuildContext
  File "/home/runner/work/_temp/setup-sam-43osIE/.venv/lib/python3.10/site-packages/samcli/commands/build/build_context.py", line 13, in <module>
    from samcli.lib.providers.sam_api_provider import SamApiProvider
  File "/home/runner/work/_temp/setup-sam-43osIE/.venv/lib/python3.10/site-packages/samcli/lib/providers/sam_api_provider.py", line 6, in <module>
    from samcli.lib.providers.api_collector import ApiCollector
  File "/home/runner/work/_temp/setup-sam-43osIE/.venv/lib/python3.10/site-packages/samcli/lib/providers/api_collector.py", line 10, in <module>
    from samcli.local.apigw.local_apigw_service import Route
  File "/home/runner/work/_temp/setup-sam-43osIE/.venv/lib/python3.10/site-packages/samcli/local/apigw/local_apigw_service.py", line 11, in <module>
    from flask import Flask, request
  File "/home/runner/work/_temp/setup-sam-43osIE/.venv/lib/python3.10/site-packages/flask/__init__.py", line 14, in <module>
    from jinja2 import escape
  File "/home/runner/work/_temp/setup-sam-43osIE/.venv/lib/python3.10/site-packages/jinja2/__init__.py", line 12, in <module>
    from .environment import Environment
  File "/home/runner/work/_temp/setup-sam-43osIE/.venv/lib/python3.10/site-packages/jinja2/environment.py", line 25, in <module>
    from .defaults import BLOCK_END_STRING
  File "/home/runner/work/_temp/setup-sam-43osIE/.venv/lib/python3.10/site-packages/jinja2/defaults.py", line 3, in <module>
    from .filters import FILTERS as DEFAULT_FILTERS  # noqa: F[40](https://github.com/mensabrands/dip-app/runs/5243143255?check_suite_focus=true#step:5:40)1
  File "/home/runner/work/_temp/setup-sam-[43](https://github.com/mensabrands/dip-app/runs/5243143255?check_suite_focus=true#step:5:43)osIE/.venv/lib/python3.10/site-packages/jinja2/filters.py", line 13, in <module>
    from markupsafe import soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/home/runner/work/_temp/setup-sam-43osIE/.venv/lib/python3.10/site-packages/markupsafe/__init__.py)
```

I revert sam-cli version to `1.37.0` and it worked perfectly.

**Comment by oeoen** [comment]
I tried to change the version of sam to 1.29.0 in github actions using this [action](https://github.com/aws/aws-sam-cli), seemslike it still download the newest version of Markupsafe

**Comment by olmolod** [comment]
@sthadapradit   this I did, but it is temproary solution  - any idea how to come back to 
pip install --user --upgrade aws-sam-cli 
insted 
pip install --user  aws-sam-cli ==1.37.0

**Comment by BCarley** [comment]
Looks like a breaking change in `markupsafe` and `jinja` not specifying an upper version bound https://github.com/pallets/markupsafe/issues/286

**Comment by Yop-La** [comment]
I'm getting the same error with "SAM CLI, version 1.37.0"

**Comment by MurphyAdam** [comment]
I had this issue with Django using Jinja2. Jinja2 imports `soft_unicode` from the package causing it to break.

**Comment by Yop-La** [comment]
Downgrading markupsafe to 2.0.1 fixes the issue on my side?

**Comment by davidism** [comment]
aws-sam-cli is using an unsupported version of Jinja, they need to update to the latest version. Additionally, they need to read https://hynek.me/articles/semver-will-not-save-you/, then use a tool like [pip-tools](https://pypi.org/project/pip-tools/) to pin their  dependencies to control when their users get updates. Be sure to run tests with deprecation warnings treated as errors so that these types of changes show up early.

**Comment by jfuss** [comment]
Looking into this. Though this is why we do not recommend using pip to install and instead use our installers.

@davidism We are stuck in a place that if we pin, customers get upset that they can install with all their other tools (in a single interpreter instead of isolating). If we don't pin (everything), we run into this things. So it's a who do we block/make angry situation. Would be great if python (pip) actually solved this instead of each tool having to battle users on how to install or providing ways tools can vend safely through pip.

**Comment by codybc** [comment]
Just ran into this issue using `aws-actions/setup-sam@v1`

easy fix if anyone else sees this though, setup-sam allows you to set version

```
- uses: aws-actions/setup-sam@v1
        with:
          version: 1.37.0
```

**Comment by mndeveci** [comment]
Thanks for reporting this issue. SAM CLI v1.38.1 is released which contains the fix for it. As @jfuss mentioned, we would highly recommend using our installers (NativeInstaller for Linux, brew for MacOS and MSI for Windows). 

Resolving the issue.

**Comment by Rilee991** [comment]
I faced the same issue as well, my sam version is 1.38.1.
I resolved it by 
1. Uninstalling the sam
brew uninstall aws-sam-cli
2. Installing pip
brew install python
3. downloading markupsafe version 2.0.1
pip3 install markupsafe==2.0.1

Hope it helps!

**Comment by MurphyAdam** [comment]
> I faced the same issue as well, my sam version is 1.38.1. I resolved it by
> 
>     1. Uninstalling the sam
>        brew uninstall aws-sam-cli
> 
>     2. Installing pip
>        brew install python
> 
>     3. downloading markupsafe version 2.0.1
>        pip3 install markupsafe==2.0.1
> 
> 
> Hope it helps!

you don't need to do uninstall pip, just download markupsafe==2.0.1

**Comment by BoHuang2018** [comment]
> pip install markupsafe==2.0.1

Yes, this is the solution. An little complement, if you have installed `MarkupSafe-2.1.0` (like me), `pip install markupsafe==2.0.1` will return the following error:
`ERROR: Could not install packages due to an OSError: Cannot move the non-empty directory '...path.../venv/lib/python3.9/site-packages/MarkupSafe-2.1.0.dist-info/'`

Solution is to uninstall the existed `MarkupSafe-2.1.0` by command: `sudo pip uninstall markupsafe `

In my workstation, I walked through the following two steps:

1.  Uninstall the existed  `markupsafe-2.1.0`
`sudo pip uninstall markupsafe`
2. Install `markupsafe-2.0.1`
`pip install markupsafe==2.0.1`

**Comment by Alialhaj77** [comment]
could you please write the perfect solution for this issue , I've tried most of them but no luck

**Comment by BoHuang2018** [comment]
> could you please write the perfect solution for this issue , I've tried most of them but no luck

To be honest, there is no perfect solution, because it depends on your environmental configuration.  
What is the error on your machine ?

**Comment by Alialhaj77** [comment]
I have tried to install ERPnext 13 more than 20 times , using all the tutorials but no good result ,
when I use Easy install [ sudo python3 install.py --verbose --production --user [USER] --mariadb-version 10.5 --frappe-branch version-13 --erpnext-branch version-13 ]
I got error , return none zero status 2

Could you please help me out

**Comment by Alialhaj77** [comment]
the whole result 

fatal: [localhost]: FAILED! => {
    "changed": true,
    "cmd": [
        "bench",
        "init",
        "/home/frappe/frappe-bench",
        "--frappe-path",
        "https://github.com/frappe/frappe",
        "--frappe-branch",
        "version-13",
        "--python",
        "python3"
    ],
    "delta": "0:00:00.378029",
    "end": "2022-02-20 10:45:29.953302",
    "invocation": {
        "module_args": {
            "_raw_params": "bench init /home/frappe/frappe-bench --frappe-path https://github.com/frappe/frappe --frappe-branch version-13 --python python3",
            "_uses_shell": false,
            "argv": null,
            "chdir": null,
            "creates": "/home/frappe/frappe-bench",
            "executable": null,
            "removes": null,
            "stdin": null,
            "stdin_add_newline": true,
            "strip_empty_ends": true,
            "warn": true
        }
    },
    "msg": "non-zero return code",
    "rc": 1,
    "start": "2022-02-20 10:45:29.575273",
    "stderr": "Traceback (most recent call last):\n  File \"/usr/bin/bench\", line 33, in <module>\n    sys.exit(load_entry_point('frappe-bench', 'console_scripts', 'bench')())\n  File \"/usr/bin/bench\", line 22, in importlib_load_entry_point\n    for entry_point in distribution(dist_name).entry_points\n  File \"/usr/lib/python3.8/importlib/metadata.py\", line 503, in distribution\n    return Distribution.from_name(distribution_name)\n  File \"/usr/lib/python3.8/importlib/metadata.py\", line 177, in from_name\n    raise PackageNotFoundError(name)\nimportlib.metadata.PackageNotFoundError: frappe-bench",
    "stderr_lines": [
        "Traceback (most recent call last):",
        "  File \"/usr/bin/bench\", line 33, in <module>",
        "    sys.exit(load_entry_point('frappe-bench', 'console_scripts', 'bench')())",
        "  File \"/usr/bin/bench\", line 22, in importlib_load_entry_point",
        "    for entry_point in distribution(dist_name).entry_points",
        "  File \"/usr/lib/python3.8/importlib/metadata.py\", line 503, in distribution",
        "    return Distribution.from_name(distribution_name)",
        "  File \"/usr/lib/python3.8/importlib/metadata.py\", line 177, in from_name",
        "    raise PackageNotFoundError(name)",
        "importlib.metadata.PackageNotFoundError: frappe-bench"
    ],
    "stdout": "",
    "stdout_lines": []
}

PLAY RECAP *****************************************************************************************************************************************************************
localhost                  : ok=67   changed=17   unreachable=0    failed=1    skipped=62   rescued=0    ignored=0   

Traceback (most recent call last):
  File "install.py", line 497, in <module>
    install_bench(args)
  File "install.py", line 278, in install_bench
    run_playbook('site.yml', sudo=True, extra_vars=extra_vars)
  File "install.py", line 413, in run_playbook
    success = subprocess.check_call(args, cwd=playbooks_folder, stdout=log_stream, stderr=sys.stderr)
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ansible-playbook', '-c', 'local', 'site.yml', '-vvvv', '-e', '@/tmp/extra_vars.json', '--become', '--become-user=frappe']' returned non-zero exit status 2.

**Comment by BoHuang2018** [comment]
> I have tried to install ERPnext 13 more than 20 times , using all the tutorials but no good result , when I use Easy install [ sudo python3 install.py --verbose --production --user [USER] --mariadb-version 10.5 --frappe-branch version-13 --erpnext-branch version-13 ] I got error , return none zero status 2
> 
> Could you please help me out

Sorry, it is my first time to hear about ERPnext 13 ...  Did a search, looks like a big product ....

**Comment by IrinaAlexandra** [comment]
Why has this been closed? 🤔  This is still an issue with version `1.38.1.` because of `Flask`'s dependency.

**Comment by codestacko** [comment]
For me solution 3 worked from [https://itsmycode.com/importerror-cannot-import-name-json-from-itsdangerous/](https://itsmycode.com/importerror-cannot-import-name-json-from-itsdangerous/)

I did not upgrade the Flask version to 1.1.4 which has this issue. You just have to downgrade the` itsdangerous==2.0.1` and it will fix the issue. Just add this version in your  requirements.txt file.

**Comment by juhamkilpinen** [comment]
For poetry/falcon users: This worked for me:
poetry add markupsafe=2.0.1

**Comment by frezaei-snap** [comment]
Hi,

I have the same issue, and I do not know how to fix it. I changed the jinja2 versions but it did not help:

  File "/pyroot/lib/python3.8/site-packages/jinja2/__init__.py", line 12, in <module>
    from .environment import Environment
  File "/pyroot/lib/python3.8/site-packages/jinja2/environment.py", line 25, in <module>
    from .defaults import BLOCK_END_STRING
  File "/pyroot/lib/python3.8/site-packages/jinja2/defaults.py", line 3, in <module>
    from .filters import FILTERS as DEFAULT_FILTERS  # noqa: F401
  File "/pyroot/lib/python3.8/site-packages/jinja2/filters.py", line 13, in <module>
    from markupsafe import soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/pyroot/lib/python3.8/site-packages/markupsafe/__init__.py)

**Comment by IrinaAlexandra** [comment]
> Hi,
> 
> I have the same issue, and I do not know how to fix it. I changed the jinja2 versions but it did not help:
> 
> File "/pyroot/lib/python3.8/site-packages/jinja2/**init**.py", line 12, in from .environment import Environment File "/pyroot/lib/python3.8/site-packages/jinja2/environment.py", line 25, in from .defaults import BLOCK_END_STRING File "/pyroot/lib/python3.8/site-packages/jinja2/defaults.py", line 3, in from .filters import FILTERS as DEFAULT_FILTERS # noqa: F401 File "/pyroot/lib/python3.8/site-packages/jinja2/filters.py", line 13, in from markupsafe import soft_unicode ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/pyroot/lib/python3.8/site-packages/markupsafe/**init**.py)

Try pinning markupsafe to 2.0.1

**Comment by frezaei-snap** [comment]
> markupsafe

Thank you for your response. I am not using markupsafe directly. How can I pin it?

**Comment by Tati1701** [comment]
> > markupsafe
> 
> Thank you for your response. I am not using markupsafe directly. How can I pin it?

Like  mentioned above in https://github.com/aws/aws-sam-cli/issues/3661#issuecomment-1044340547, you can "pin" it by adding the version number explicitly (`markupsafe==2.0.1`) in your pip install:

`pip install markupsafe==2.0.1`

It works the same when you're installing something else:

`pip install something_that_depends_on_markupsafe_transitively markupsafe==2.0.1`

See: https://stackoverflow.com/questions/44448925/how-to-pin-transitive-dependencies-with-setup-py-in-python

**Comment by frezaei-snap** [comment]
I did this, but it did not help. I am still getting the same error.

**Comment by dat-linux** [comment]
Other software depends on this package, so breaking backwards compat. is going to break all those other apps. Please don;t do this.

**Comment by parvathirajan** [comment]
I'm having `2.0.1` everywhere but still, this breaks the application. Any solution? 

After `1.40.0` ✋🏻 

```shell
(env) [DOMAIN\par3836@sys pro]$ python -m pip freeze | grep -i markupsafe      
MarkupSafe==2.0.1
(env) [DOMAIN\par3836@sys pro]$ python3 -m pip freeze | grep -i markupsafe
MarkupSafe==2.0.1
```

**Comment by IrinaAlexandra** [comment]
How I solved it is after all the project dependencies are installed, I do a  'pip uninstall -y markupsafe ' and then a  'pip install markupsafe==2.0.1 '. Hope this helps someone.

**Comment by mikhail-khoroshev** [comment]
Thank you guys! Downgrade to 2.0.1 resolved an issue!

**Comment by dominicHalo** [comment]
> I'm having `2.0.1` everywhere but still, this breaks the application. Any solution?
> 
> After `1.40.0` ✋🏻
> 
> ```shell
> (env) [DOMAIN\par3836@sys pro]$ python -m pip freeze | grep -i markupsafe      
> MarkupSafe==2.0.1
> (env) [DOMAIN\par3836@sys pro]$ python3 -m pip freeze | grep -i markupsafe
> MarkupSafe==2.0.1
> ```

@parvathirajan what is the error you are seeing? Is the markup safe dependancy that is at version 2.0.1 at the BOTTOM of your requirements file? make sure it is installed last, so it just overwrites any old versions. if you don't, the correct version will be overwritten by the incorrect version.

**Comment by samamorgan** [comment]
I'm having this issue both locally using the VSCode AWS Toolkit and `aws-actions/setup-sam@v1`. No matter what I try from this thread, I still hit the error.

**Comment by dat-linux** [comment]
> I'm having this issue both locally using the VSCode AWS Toolkit and `aws-actions/setup-sam@v1`. No matter what I try from this thread, I still hit the error.

are you in the virtual env when you do the fix?

**Comment by birdybro** [comment]
https://github.com/MiSTer-devel/MkDocs_MiSTer/commit/582344887b2d7afb60fefdf9d92cf151878a7646

This just caused a problem for me too, and I had to update as well. Thank you!

**Comment by jrg94** [comment]
For anyone finding this organically through search, I added an upper bound to the MarkupSafe dependency at the top of my requirements.txt file (if that's something you're using). 

```text
MarkupSafe<2.1.0
```

My GitHub Actions workflow uses the requirements file to setup testing, so this made life a bit easier. I imagine @Yop-La's solution (https://github.com/aws/aws-sam-cli/issues/3661#issuecomment-1044340547) would work just as well.

**Comment by andrewsilberfeld** [comment]
> Downgrading markupsafe to 2.0.1 fixes the issue on my side. `pip install markupsafe==2.0.1`

This worked for me too when creating a python env from my yaml file!

**Comment by Narenderbeniwal** [comment]
This Issue can be solve using below for steps:
1. pip install MarkupSafe
2. pip install markupsafe==2.0.1
3. pip install --user --upgrade aws-sam-cli
4. pip install --user --upgrade aws-sam-cli

**Comment by Prathamrajgor** [comment]
> pip install markupsafe==2.0.1

Thanks Buddy, It worked.

**Comment by sandeepsanwal93** [comment]
its working fine

pip install markupsafe==2.0.1

**Comment by ArchaeonSeq** [comment]
None of these solutions are working for me.

**Comment by Amanrajdas01** [comment]
> same here - seems MarkUoSafe was updated and there is no soft_unicode there any more. How to solve this?
> 
> ```
> `- step: &build_stage
>             name: build
>             image: python:3.9
>             script:
>                 - apt-get update && apt-get install -y python3-pip zip 
>                 - pip install -U awscli
>                 - aws --version
>                 - aws configure set default.region $AWS_DEFAULT_REGION
>                 - aws configure set aws_access_key_id "$AWS_ACCESS_KEY_ID_STAGE"
>                 - aws configure set aws_secret_access_key "$AWS_SECRET_ACCESS_KEY_STAGE"
>                 - pip install --user --upgrade aws-sam-cli
>                 - ln -s /root/.local/bin/sam /usr/bin/sam
>                 - sam --version
>                 - sam build`
> ```
> 
> pip install --user --upgrade aws-sam-cli - gets last version on Jijnja
> 
> Collecting Jinja2<4.0.0,>=2.7 Using cached Jinja2-3.0.3-py3-none-any.whl (133 kB)
> 
> yesterday was Collecting Jinja2<4.0.0,>=2.7 Using cached Jinja2-2.11.3-py2.py3-none-any.whl (125 kB)

thankyou, it works

**Comment by SamarShabanCS** [comment]
> Downgrading markupsafe to 2.0.1 fixes the issue on my side. `pip install markupsafe==2.0.1`

Thanks a lot.
It solved the problem

**Comment by fpena06** [comment]
> Downgrading markupsafe to 2.0.1 fixes the issue on my side. `pip install markupsafe==2.0.1`

thank you.
